### ISSUE TITLE
Images not stored

### ISSUE THREAD

**Issue by ballesta** [SanishGrg/Laravel-Notebook#2]
Problem when attempting to add an image to a note using the WYSIWYG editor:

- The image selection works fine

- The image is not shown in editor

I guess it has to do with 'storage' folder:

- Command "php artisan storage:link" executed

- Excerpt of 'filesystem.php':

>    'disks' => [

        'local' => [
            'driver' => 'local',
            'root' => storage_path('app'),
        ],

        'public' => [
            'driver' => 'local',
            'root' => storage_path('app/public'),
            'url' => env('APP_URL').'/storage',
            'visibility' => 'public',
        ],

Best regards
Bernard

**Comment by sanz** [comment]
File upload adapter is added to the content WYSIWYG editor.
